language: php

php:
  - 5.6
  - 7.0

env:
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="dev-master@dev"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: eugone.yann@gmail.com
